- name: Install Flask and Gunicorn
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3 pip
      apt:
        name: python3-pip
        state: latest

    - name: Install Flask
      pip:
        name: flask
        state: latest

    - name: Install Gunicorn
      apt:
        name: gunicorn
        state: latest

    - name: Copy Application2.py
      copy:
        src: "{{ playbook_dir }}/application2.py"
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Run Flask application
      command: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app

- name: Configure HAProxy
  hosts: HAproxy
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: "{{ playbook_dir }}/haproxy.cfg.j2"
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
